git clone https://github.com/mapillary/inplace_abn.git
Cloning into 'inplace_abn'...
remote: Enumerating objects: 762, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 762 (delta 60), reused 113 (delta 49), pack-reused 629
Receiving objects: 100% (762/762), 347.29 KiB | 269.00 KiB/s, done.
Resolving deltas: 100% (446/446), done.
❯ cd inplace_abn
❯ python setup.py install
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running install
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating inplace_abn.egg-info
writing inplace_abn.egg-info/PKG-INFO
writing dependency_links to inplace_abn.egg-info/dependency_links.txt
writing top-level names to inplace_abn.egg-info/top_level.txt
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'inplace_abn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-39
creating build/lib.linux-x86_64-cpython-39/inplace_abn
copying inplace_abn/group.py -> build/lib.linux-x86_64-cpython-39/inplace_abn
copying inplace_abn/__init__.py -> build/lib.linux-x86_64-cpython-39/inplace_abn
copying inplace_abn/functions.py -> build/lib.linux-x86_64-cpython-39/inplace_abn
copying inplace_abn/abn.py -> build/lib.linux-x86_64-cpython-39/inplace_abn
copying inplace_abn/_version.py -> build/lib.linux-x86_64-cpython-39/inplace_abn
running build_ext
building 'inplace_abn._backend' extension
creating build/temp.linux-x86_64-cpython-39
creating build/temp.linux-x86_64-cpython-39/src
gcc -pthread -B /home/manan/anaconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/manan/anaconda3/envs/pytorch/include -I/home/manan/anaconda3/envs/pytorch/include -fPIC -O2 -isystem /home/manan/anaconda3/envs/pytorch/include -fPIC -DWITH_CUDA=1 -I/home/manan/projects/MiB/inplace_abn/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/manan/anaconda3/envs/pytorch/include/python3.9 -c src/inplace_abn.cpp -o build/temp.linux-x86_64-cpython-39/src/inplace_abn.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
In file included from /home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:14,
                 from /home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
                 from /home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                 from src/inplace_abn.cpp:6:
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<Activation>’:
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:2134:7:   required from ‘class pybind11::enum_<Activation>’
src/inplace_abn.cpp:205:46:   required from here
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: ‘pybind11::class_<Activation>’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
 1479 | class class_ : public detail::generic_type {
      |       ^~~~~~
gcc -pthread -B /home/manan/anaconda3/envs/pytorch/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/manan/anaconda3/envs/pytorch/include -I/home/manan/anaconda3/envs/pytorch/include -fPIC -O2 -isystem /home/manan/anaconda3/envs/pytorch/include -fPIC -DWITH_CUDA=1 -I/home/manan/projects/MiB/inplace_abn/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/TH -I/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/manan/anaconda3/envs/pytorch/include/python3.9 -c src/inplace_abn_cpu.cpp -o build/temp.linux-x86_64-cpython-39/src/inplace_abn_cpu.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Traceback (most recent call last):
  File "/home/manan/projects/MiB/inplace_abn/setup.py", line 48, in <module>
    setuptools.setup(
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 549, in build_extension
    objects = self.compiler.compile(
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/manan/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range